from enum import Enum


class WaitType(Enum):
    WAIT_FOR_VISIBILITY_OF_ELEMENT_LOCATED = 1
    WAIT_FOR_INVISIBILITY_OF_ELEMENT_LOCATED = 2
    WAIT_FOR_ELEMENT_TO_BE_PRESENTED = 3
    WAIT_FOR_ELEMENTS_TO_BE_PRESENTED = 4
    WAIT_FOR_ELEMENTS_TO_BE_CLICKABLE = 5
